### ISSUE TITLE
Fatal error: Declaration of Invoicing\Moloni\Model\Documents::setCompanyId($companyId)

### ISSUE THREAD

**Issue by nitaipanda** [moloni/magento2#1]
Fatal error: Declaration of Invoicing\Moloni\Model\Documents::setCompanyId($companyId) must be compatible with Invoicing\Moloni\Api\Data\DocumentsInterface::setCompanyId(int $companyId) in /home/websteptechco/pegada27.websteptech.co.uk/app/code/Invoicing/Moloni/Model/Documents.php on line 28

**Comment by nitaipanda** [comment]
please provide the solution as soon as possible.

**Comment by moloni-pt** [comment]
Hello, 

Updated the master branch with a fix to this issue. 
The document model did not have the param type. 

Please download the master files and replace yours

**Comment by nitaipanda** [comment]
please provide the master file link.
