### ISSUE TITLE
please provide master file link

### ISSUE THREAD

**Issue by nitaipanda** [moloni/magento2#3]
Fatal error: Declaration of Invoicing\Moloni\Model\Documents::setCompanyId($companyId)

**Comment by nitaipanda** [comment]
please give master file link as soon as possible.

**Comment by moloni-pt** [comment]
This was the change made: 
https://github.com/moloni/magento2/commit/d137a2f6b68ffc62824fccbc9413a360b38f8cbf#diff-62254d92cabfcc3e284b939b19a75e32
