### ISSUE TITLE
Errro ao inserir o artigo: B&B1005

### ISSUE THREAD

**Issue by nitaipanda** [moloni/magento2#5]
![image](https://user-images.githubusercontent.com/20333565/63924332-b5ac8200-ca65-11e9-96bd-0ccae8f404ec.png)
 Please where is the problem?
sow this error.

**Comment by nitaipanda** [comment]
we can not understand this error.please help me

**Comment by moloni-pt** [comment]
Hello, 
The console log show every request made to our API and if you click on each of the links, it will show you all the values sent to our API and the values received. 

Please click on the documents/insert URL to see the values our API is sending you. 
Those values have the error. 

Also please try to update the plugin.
