### ISSUE TITLE
Compatibilidade com Magento 2.4

### ISSUE THREAD

**Issue by jfabiano** [moloni/magento2#6]
Esta versão é compatível com Magento 2.4? Instalei segundo as instruções e não me apareceu qualquer sub-menu no menu Sales. Já alguém testou com a versão 2.4? 

Obrigado

**Comment by moloni-pt** [comment]
Boa tarde, 

Temos o plugin a funcionar correctamente mesma na versão 2.4 do Magento. 
Pode confirmar se já seguiu os passos completos indicados em: https://github.com/moloni-pt/magento2#install-guide-using-composer 

E se o plugin se encontra activo?

**Comment by jfabiano** [comment]
Olá. Segui todos os passos e o plugin encontra-se activo. Mas sempre que vou ao menu Sales não aparece nada referente ao Moloni.

**Comment by jfabiano** [comment]
Experimentei na versão 2.3.5 e acontece o mesmo problema. É estranho pois o plugin está activo.

**Comment by moloni-pt** [comment]
Bom dia, 

Tem possibilidade de verificar se a conta que está a usar no Magento tem acesso ao plugin Moloni?
Verifique por favor se lhe aparece o plugin Moloni no grupo de permissões associado ao seu utilizador.

**Comment by jfabiano** [comment]
Bom dia.

Continua a não aparecer. Está instalado e activo mas não aparece lá no
menu.

A segunda, 7 de set de 2020, 12:04, Moloni Portugal <
notifications@github.com> escreveu:

**Comment by moloni-pt** [comment]
Bom dia, 

Lançámos agora mesmo um update para a versão 1.3.0 que já permite a compatibilidade do plugin com a versão 2.4.2 do Magento. 

Pode agora atualizar o plugin para a última versão.
