### ISSUE TITLE
Sincronizar todos os produtos e stocks da loja

### ISSUE THREAD

**Issue by jfabiano** [moloni/magento2#7]
É possível sincronizar todos os produtos e stocks do Magento (2.3.5), mesmo que ainda não hajam vendas?

**Comment by moloni-pt** [comment]
Boa tarde, 

Infelizmente de momento essa funcionalidade não está planeada. 
O plugin dispõe de uma opção para criar/atualizar o artigo no Moloni sempre que um artigo é criado/atualizado no Magento, no entanto, não é possível inserir os artigos de forma massiva. 

Essa importação de forma massiva podia também ter interferência com as lojas online devido à carga que podia causar e ao tempo que podia demorar,, pelo que optámos numa primeira fase por não implementar a funcionalidade. 

No entanto, existe sempre a possibilidade de exportar os artigos do Magento para um ficheiro CSV ou Excel e usar a nossa ferramenta de importação para importar os artigos ou atualizar os mesmos de forma massiva. 

Pode consultar a seguinte FAQ sobre essa mesma questão: 
https://www.moloni.pt/suporte/index.php?action=getFaqDetail&id=115

**Comment by jfabiano** [comment]
Boa tarde,

Muito obrigado pela resposta. Dessa forma já ajuda bastante. 

Só mais uma questão: eu tenho as sincronizações ativas (stocks e preços). No entanto, criei um novo produto no Magento e o mesmo não aparece no Moloni.  Como posso ativar essa opção? 

Muito obrigado.
